# Generated by Django 2.0.4 on 2018-04-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_categorie_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
