# Generated by Django 2.0.4 on 2018-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20180420_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.TextField(default='#37474F', max_length=30),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='color',
            field=models.CharField(default='#37474F', max_length=30),
        ),
    ]
