# Generated by Django 2.0.4 on 2018-04-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20180420_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Publisher'),
            preserve_default=False,
        ),
    ]
