# Generated by Django 2.0.4 on 2018-04-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_categorie_tab id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='Tab id',
            new_name='tabHome',
        ),
    ]
