# Generated by Django 2.0.4 on 2018-04-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180420_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='tabHome',
            new_name='Tab id',
        ),
    ]
