# Generated by Django 2.0.4 on 2018-04-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20180420_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='Tab id',
            new_name='tabHome',
        ),
    ]
