# Generated by Django 2.0.4 on 2018-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20180421_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='resume',
            field=models.TextField(default='Populo tritani laboramus ex mei, no eum iuvaret ceteros euripidis, ne alia sadipscing mei. Te inciderint cotidieque pro, ei iisque docendi qui, ne accommodare theophrastus reprehendunt vel. Et commodo menandri eam'),
        ),
    ]
