# Generated by Django 2.0.4 on 2018-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_news_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
