# Generated by Django 2.0.4 on 2018-04-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20180421_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
