# Generated by Django 2.0.4 on 2018-04-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.News')),
                ('videoUrl', models.URLField(default=False)),
            ],
            bases=('journal.news',),
        ),
    ]
