# Generated by Django 2.0.4 on 2018-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.URLField(),
        ),
    ]
