# Generated by Django 2.0.4 on 2018-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_remove_video_imagevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagevideo',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='ImageVideo',
        ),
    ]
