# Generated by Django 2.0.4 on 2018-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20180422_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='nombreComment',
            field=models.IntegerField(default=0),
        ),
    ]
