# Generated by Django 2.0.4 on 2018-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_news_nombrecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='emaim',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
