# Generated by Django 2.0.4 on 2018-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_commentaire_emaim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='emaim',
            new_name='email',
        ),
    ]
