# Generated by Django 2.0.4 on 2018-04-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.News'),
            preserve_default=False,
        ),
    ]
