# Generated by Django 2.0.4 on 2018-04-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_signalcomment_signalreponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalcomment',
            old_name='comment',
            new_name='commentaire',
        ),
    ]
