# Generated by Django 2.0.4 on 2018-04-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0031_auto_20180425_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='nombreComment',
        ),
    ]
