# Generated by Django 2.0.4 on 2018-04-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0032_remove_news_nombrecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='news',
        ),
    ]
