# Generated by Django 2.0.4 on 2018-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0035_auto_20180429_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
