# Generated by Django 2.0.4 on 2018-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0039_publisher_datecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='promo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
