# Generated by Django 2.0.4 on 2018-05-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0040_video_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='promo',
        ),
        migrations.AlterField(
            model_name='news',
            name='smallTitre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
