# Generated by Django 2.0.4 on 2018-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0042_remove_news_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='data_merge',
            field=models.IntegerField(default=2),
        ),
    ]
