# Generated by Django 2.0.4 on 2018-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0048_auto_20180504_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_enable',
            field=models.BooleanField(default=True),
        ),
    ]
