# Generated by Django 2.0.4 on 2018-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0049_news_comment_enable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newslatter',
            new_name='Newsletter',
        ),
        migrations.AlterField(
            model_name='news',
            name='comment_enable',
            field=models.BooleanField(default=True, verbose_name='Activer les commentaires'),
        ),
    ]
