# Generated by Django 2.0.4 on 2018-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0053_auto_20180505_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tabHome',
            new_name='tab_home',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='datePublication',
            new_name='date_publication',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imagePrincipale',
            new_name='primary_image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='smallTitre',
            new_name='small_title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='nombreVue',
            new_name='view_number',
        ),
    ]
