# Generated by Django 2.0.4 on 2018-05-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0054_auto_20180505_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='datePublication',
            new_name='date_publication',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='nomComplet',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='nombreLike',
            new_name='number_like',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='commentaire',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='datePublication',
            new_name='date_publication',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='nomComplet',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='nombreLike',
            new_name='number_like',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='equipe_selection',
            new_name='team_selection',
        ),
    ]
