# Generated by Django 2.0.4 on 2018-05-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0055_auto_20180505_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reponse',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='Comment',
        ),
    ]
