# Generated by Django 2.0.4 on 2018-05-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0056_auto_20180505_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('motif', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='signalreponse',
            name='reponse',
        ),
        migrations.RenameField(
            model_name='journalist',
            old_name='photo_de_profil',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='signalcomment',
            old_name='commentaire',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='signalcomment',
            old_name='dateEnvoi',
            new_name='date_send',
        ),
        migrations.DeleteModel(
            name='SignalReponse',
        ),
    ]
