# Generated by Django 2.0.4 on 2018-05-05 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0057_auto_20180505_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publisher',
            new_name='journalist',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
