# Generated by Django 2.0.4 on 2018-05-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0058_auto_20180505_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalanswer',
            old_name='motif',
            new_name='cause',
        ),
        migrations.RenameField(
            model_name='signalcomment',
            old_name='motif',
            new_name='cause',
        ),
    ]
