# Generated by Django 2.0.4 on 2018-05-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0059_auto_20180505_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videoUrl',
            new_name='video_url',
        ),
    ]
