# Generated by Django 2.0.4 on 2018-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0060_auto_20180505_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='null'),
        ),
    ]
