# Generated by Django 2.0.4 on 2018-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_auto_20180506_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
