# Generated by Django 2.0.4 on 2018-05-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0064_auto_20180507_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='active',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='last_name',
        ),
    ]
