# Generated by Django 2.0.4 on 2018-05-10 15:42

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_auto_20180507_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='share_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/05/10')),
        ),
    ]
