# Generated by Django 2.0.4 on 2018-05-11 18:36

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0067_auto_20180510_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.Image')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.News')),
            ],
            bases=('journal.image',),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=journal.models.PathAndRename('images/2018/05/11')),
        ),
    ]
