# Generated by Django 2.0.4 on 2018-05-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0068_auto_20180511_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenews',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.News'),
        ),
    ]
