# Generated by Django 2.0.4 on 2018-05-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0069_auto_20180511_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
