# Generated by Django 2.0.4 on 2018-05-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0071_auto_20180512_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
